### Problem Statement:

One of the aspects Seattle is most notable for, in addition to coffee, grunge, and electronic businesses, is its rains. From January 1, 1948 to December 12, 2017, this dataset provides full records of Seattle's daily rainfall patterns.

### Data Dictionary

- Following are the variables with their definition and key:

    - DATE: The date of the observation

    - PRCP: The amount of precipitation, in inches

    - TMAX: The maximum temperature for that day, in degrees Fahrenheit

    - TMIN: The minimum temperature for that day, in degrees Fahrenheit

    - RAIN: TRUE if rain was observed on that day, FALSE if it was not

#### 1) Importing Necessary Libraries:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
from sklearn.metrics import ConfusionMatrixDisplay, RocCurveDisplay

#### 2) Loading Data:

In [2]:
df = pd.read_csv('seattleWeather_1948-2017.csv')

In [3]:
df.head()

         DATE  PRCP  TMAX  TMIN  RAIN
0  1948-01-01  0.47    51    42  True
1  1948-01-02  0.59    45    36  True
2  1948-01-03  0.42    45    35  True
3  1948-01-04  0.31    45    34  True
4  1948-01-05  0.17    45    32  True

In [4]:
df.shape

(25551, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25551 entries, 0 to 25550
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    25551 non-null  object
 1   PRCP    25548 non-null  float64
 2   TMAX    25551 non-null  int64
 3   TMIN    25551 non-null  int64
 4   RAIN    25548 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 998.2+ KB

In [6]:
df.describe()

               PRCP          TMAX          TMIN
count  25548.000000  25551.000000  25551.000000
mean       0.106222     59.544206     44.514226
std        0.239031     12.772984      8.892836
min        0.000000      4.000000      0.000000
25%        0.000000     50.000000     38.000000
50%        0.000000     58.000000     45.000000
75%        0.100000     69.000000     52.000000
max        5.020000    103.000000     71.000000

#### 3) Data Cleaning and Transformations:

In [10]:
df.head()

         DATE  PRCP  TMAX  TMIN  RAIN
0  1948-01-01  0.47    51    42  True
1  1948-01-02  0.59    45    36  True
2  1948-01-03  0.42    45    35  True
3  1948-01-04  0.31    45    34  True
4  1948-01-05  0.17    45    32  True

##### 1) Handling Missing Values:

In [12]:
df.isna().sum() / len(df) * 100

DATE    0.000000
PRCP    0.011741
TMAX    0.000000
TMIN    0.000000
RAIN    0.011741
dtype: float64

- There are 3 Missing Values for "PRCP" and 'RAIN' columns.

In [13]:
df[df['PRCP'].isna()]

             DATE  PRCP  TMAX  TMIN RAIN
18415  1998-06-02   NaN    72    52  NaN
18416  1998-06-03   NaN    66    51  NaN
21067  2005-09-05   NaN    70    52  NaN

- As we can see, Same 3 rows has 'PRCP' and 'RAIN' features missing.
- We can drop this 3 rows.

In [14]:
df = df.dropna()

In [15]:
df.isna().sum()

DATE    0
PRCP    0
TMAX    0
TMIN    0
RAIN    0
dtype: int64

- Missing Values are Taken Care of.
- For all the features, we will go feature by feature to check what king of Transformations are needed.

##### 2) DATE: