# Train Test Spilt:

Train-test split is a fundamental technique in machine learning used to evaluate the performance of a model and ensure its ability to generalize to unseen data. It involves dividing a dataset into two distinct subsets: a training set and a testing set.

- Purpose: The primary purpose of the train-test split is to prevent overfitting and provide an unbiased evaluation of a model's performance.
    - Training Set: This subset of the data is used to train the machine learning model. The model learns patterns, relationships, and parameters from this data.
    - Testing Set: This subset, which the model has never seen during training, is used to evaluate the model's performance on new, unseen data. This provides an indication of how well the model will generalize in a real-world scenario.

- Process:
    - Data Division: The original dataset is divided into training and testing sets, typically using a ratio like 70:30, 80:20, or 90:10, where the larger portion is allocated for training.
    - Model Training: The machine learning model is trained exclusively on the training data.
    - Model Evaluation: After training, the model's performance is evaluated using the testing set. The model makes predictions on the independent variables (features) of the testing set, and these predictions are then compared to the actual values (labels) in the testing set to calculate performance metrics (e.g., accuracy, precision, recall, mean squared error).

- Considerations:
    - Random Splitting: For most datasets, a random split is crucial to ensure that both the training and testing sets are representative of the overall data distribution.
    - Stratified Sampling: In cases of imbalanced datasets (e.g., classification problems with unequal class distributions), stratified sampling can be used to ensure that the proportion of each class is maintained in both the training and testing sets.
    - Time-Series Data: For time-series data, a chronological split is typically preferred, where earlier data is used for training and later data for testing, to simulate real-world prediction scenarios.
    - Validation Set (Optional): For more complex models or hyperparameter tuning, a third subset, called a validation set, can be introduced. The validation set is used during the model development phase to tune hyperparameters and prevent overfitting to the training data. The testing set is then reserved for the final, unbiased evaluation.

#### Example:

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:
rng = np.random.default_rng()

In [11]:
df = pd.DataFrame({'Age': rng.integers(low= 18, high= 80, size= 100),
                  'Salary': rng.integers(low= 20000, high= 100000, size= 100),
                  'is_customer': rng.integers(low= 0, high= 2, size= 100)})

In [12]:
df

    Age  Salary  is_customer
0    73   39510            0
1    53   50504            1
2    68   67652            1
3    68   47447            1
4    24   82485            1
..  ...     ...          ...
95   28   68262            1
96   40   55213            1
97   76   22114            1
98   21   21163            1
99   56   73026            0

[100 rows x 3 columns]

In [16]:
# Features:
X = df.drop('is_customer', axis= 1)
X

    Age  Salary
0    73   39510
1    53   50504
2    68   67652
3    68   47447
4    24   82485
..  ...     ...
95   28   68262
96   40   55213
97   76   22114
98   21   21163
99   56   73026

[100 rows x 2 columns]

In [17]:
# Target:
y = df['is_customer']
y

0     0
1     1
2     1
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    0
Name: is_customer, Length: 100, dtype: int64

In [18]:
# Train Test Split:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

In [19]:
print(X_train.shape)
print(X_test.shape)

(80, 2)
(20, 2)

In [20]:
print(y_train.shape)
print(y_test.shape)

(80,)
(20,)

In [25]:
# X_train: Training features
X_train

    Age  Salary
55   20   99113
88   77   62174
26   50   88115
42   72   60575
69   77   90128
..  ...     ...
60   74   29911
71   60   34678
14   65   53645
92   57   61247
51   69   43590

[80 rows x 2 columns]

In [26]:
# X_test: Testing features
X_test

    Age  Salary
83   31   71712
53   29   95158
70   38   51185
45   52   99866
44   45   48295
39   59   41445
22   51   52738
80   27   25907
10   41   80286
0    73   39510
18   63   79784
30   26   21039
73   31   30623
33   29   40687
90   30   40578
4    24   82485
76   74   96927
77   20   86097
12   72   62146
31   59   43786

In [27]:
# y_train: Training target
y_train

55    0
88    0
26    0
42    1
69    0
     ..
60    0
71    1
14    1
92    1
51    1
Name: is_customer, Length: 80, dtype: int64

In [28]:
# y_test: Testing target
y_test

83    1
53    1
70    0
45    1
44    1
39    1
22    0
80    1
10    0
0     0
18    0
30    1
73    1
33    1
90    1
4     1
76    0
77    1
12    1
31    0
Name: is_customer, dtype: int64