# Feature Encoding:

Feature encoding is the process of converting categorical data (non-numeric) into a numerical format that machine learning algorithms can understand and process. This transformation is necessary because most algorithms work with numerical inputs.

Common techniques include One-Hot Encoding for nominal data and Ordinal Encoding for data with inherent order, while other methods like Target-Mean Encoding and Hashing Encoding offer different ways to represent categorical features.

#### Why Feature Encoding is Needed
- Model Compatibility: Machine learning models like linear regression and neural networks require numerical input to perform calculations and learn patterns.
- Data Representation: Encoding converts text-based categories (e.g., "Red," "Blue," "Green") into numerical values that the model can interpret meaningfully.

#### Types of Categorical Data and Encoding
- Nominal Data: Data with discrete values and no inherent order (e.g., countries, colors).
1) One-Hot Encoding: Creates new binary columns for each category, with a '1' in the column for the corresponding category and '0' elsewhere.
2) Hashing Encoding: Uses a hashing function to map categories to a fixed number of dimensions, which can be efficient for high-cardinality features. 

- Ordinal Data: Data that has a natural order or ranking (e.g., "Low," "Medium," "High" or education levels).
1) Ordinal Encoding: Assigns a unique integer to each category based on its inherent order, ensuring that the model understands the hierarchy.

#### Advanced Encoding Techniques
- Target-Mean Encoding: Replaces a category with the mean of the target variable for that category, incorporating information about the target into the feature. 
- Frequency Encoding: Replaces categories with their frequency or count in the dataset. 

#### Choosing the Right Technique
The best encoding method depends on the type of categorical data, the number of unique categories, and the specific machine learning algorithm being used.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [6]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

#### 1) Label Encoding:

- Assigns a unique integer to each category in a feature.

- Suitable for ordinal data where there's an inherent order or ranking among categories (e.g., "low," "medium," "high").

In [8]:
le = LabelEncoder()
df['Gender_Encoded'] = le.fit_transform(df['Gender'])
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Encoded
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0

In [9]:
df['Gender_Encoded'].value_counts()

Gender_Encoded
1    5457
0    4543
Name: count, dtype: int64

In [11]:
le = LabelEncoder()
df['Geography_Encoded'] = le.fit_transform(df['Geography'])
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Encoded,Geography_Encoded
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0,0
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0,2
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0,0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,2

#### 2) One-Hot Encoding:

- Converts each category into a new binary column (0 or 1).
- Suitable for nominal data where there's no inherent order among categories (e.g., "red," "blue," "green").
- Avoids implying any ordinal relationship that doesn't exist.

##### 1) using pd.get_dummies:

In [12]:
df_dummies = pd.get_dummies(data= df, columns= ['Gender', 'Geography'], drop_first= True)
df_dummies.head()

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Encoded,Geography_Encoded,Gender_Male,Geography_Germany,Geography_Spain
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,0,0,False,False,False
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,0,2,False,False,True
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,0,0,False,False,False
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,0,0,False,False,False
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,0,2,False,False,True

##### 2) Using Sklearn:

In [14]:
ohe = OneHotEncoder(sparse_output= False, drop= 'first')
gender_mat = ohe.fit_transform(df[['Gender']])
gender_mat

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [15]:
gender_df= pd.DataFrame(data= gender_mat, columns= ohe.get_feature_names_out(['Gender']))
gender_df.head()

   Gender_Male
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0

In [16]:
new_df = df.join(gender_df)
new_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Encoded,Geography_Encoded,Gender_Male
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0,0,0.0
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0,2,0.0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0,0,0.0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,0,0.0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,2,0.0

#### Choosing the Right Encoding Method:
- Ordinal data: Label Encoding or Ordinal Encoding (if order needs to be explicit).
- Nominal data: One-Hot Encoding.
- Consider the number of unique categories and potential for high dimensionality with One-Hot Encoding.
- For target-guided encoding (e.g., Mean Encoding, Leave One Out Encoding), specialized libraries like category_encoders can be used.