# Pandas:

- Pandas is fast, powerful, flexible and easy to use open source data analysis and manipulation tool.

- Pandas is a Python library.

- Pandas is used to analyze data.

In [2]:
# !pip install pandas # To install Pandas
!pip install --upgrade pandas # To upgrade Pandas to Latest Version

Requirement already satisfied: pandas in c:\users\shail\anaconda3\lib\site-packages (1.5.3)
Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/a7/e7/ae86261695b6c8a36d6a4c8d5f9b9ede8248510d689a2f379a18354b37d7/pandas-2.3.2-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-2.3.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\shail\anaconda3\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shail\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shail\anaconda3\lib\site-packages (from pandas) (2022.7)
Collecting tzdata>=2022.7 (from pandas)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/5c/23/c7abc0ca0a1526a0774eca151daeb8de62ec457e77262b66b359c3c7679e/tzdata-2025.2-py2.py3-none-any.whl.metadata
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\shail\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.3.2-cp311-cp311-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.3 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.3/11.3 MB 2.4 MB/s eta 0:00:05
   - -------------------------------------- 0.4/11.3 MB 2.8 MB/s eta 0:00:04
   - -------------------------------------- 0.6/11.3 MB 2.9 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/11.3 MB 3.1 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/11.3 MB 3.2 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.3 MB 3.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.2/11.3 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.4/11.3 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.3 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/11.3 MB 3.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/11.3 MB 3.3 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/11.3 MB 3.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/11.3 MB 3.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/11.3 MB 2.8 MB/s eta 0:00:04
   ------- -------------------------------- 2.2/11.3 MB 3.0 MB/s eta 0:00:04
   ------- -------------------------------- 2.2/11.3 MB 3.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.3 MB 3.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.3 MB 3.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.3 MB 3.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.7/11.3 MB 3.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.8/11.3 MB 3.0 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/11.3 MB 2.9 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/11.3 MB 3.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.3 MB 2.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.3/11.3 MB 2.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.3/11.3 MB 2.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.5/11.3 MB 2.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.5/11.3 MB 2.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.6/11.3 MB 2.8 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/11.3 MB 2.8 MB/s eta 0:00:03
   ------------- -------------------------- 3.8/11.3 MB 2.8 MB/s eta 0:00:03
   ------------- -------------------------- 4.0/11.3 MB 2.8 MB/s eta 0:00:03
   -------------- ------------------------- 4.1/11.3 MB 2.8 MB/s eta 0:00:03
   -------------- ------------------------- 4.2/11.3 MB 2.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.4/11.3 MB 2.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.3 MB 2.8 MB/s eta 0:00:03
   ---------------- ----------------------- 4.6/11.3 MB 2.9 MB/s eta 0:00:03
   ---------------- ----------------------- 4.8/11.3 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 4.9/11.3 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.1/11.3 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.3/11.3 MB 2.9 MB/s eta 0:00:03
   ------------------- -------------------- 5.6/11.3 MB 3.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.3 MB 3.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.9/11.3 MB 3.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.2/11.3 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.4/11.3 MB 3.1 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.3 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.0/11.3 MB 3.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.3 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 7.5/11.3 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.3 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 7.8/11.3 MB 3.3 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.3 MB 3.4 MB/s eta 0:00:01
   ----------------------------- ---------- 8.3/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.5/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 9.0/11.3 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 9.2/11.3 MB 3.5 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.3 MB 3.5 MB/s eta 0:00:01
   --------------------------------- ------ 9.5/11.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 9.9/11.3 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 10.1/11.3 MB 3.5 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.3/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.4/11.3 MB 3.5 MB/s eta 0:00:01
   ------------------------------------- -- 10.6/11.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 10.9/11.3 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 10.9/11.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  11.1/11.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  11.2/11.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 3.4 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ---------------------------------------- 0.0/347.8 kB ? eta -:--:--
   ----------------- ---------------------- 153.6/347.8 kB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 286.7/347.8 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 347.8/347.8 kB 3.1 MB/s eta 0:00:00
Installing collected packages: tzdata, pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
Successfully installed pandas-2.3.2 tzdata-2025.2

In [4]:
# importing Pandas:
import pandas as pd
import numpy as np

In [5]:
# Checking Version of Pandas Library:
print(pd.__version__)

2.3.2

In [6]:
# Reading a CSV file using Pandas:
df = pd.read_csv('Churn_Modelling.csv')

In [7]:
print(df)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

In [8]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# To see first 5 records of Data Frame:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
# To see last 5 records of Data Frame:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
# Basic Information About Dataframe:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [14]:
# Statistical Information of Numerical Columns in DataFrame:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
# All Column Names of Dataframe:
print(df.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [16]:
# Transpose of Dataframe:
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42,41,42,39,43,44,50,29,44,27,...,33,53,36,28,29,39,35,36,42,28
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [17]:
# Sorting Database based on Column(s):
df.sort_values('Age')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,9573,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0

In [18]:
df.sort_values('Balance', ascending= False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2092,2093,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
8733,8734,15714241,Haddon,749,Spain,Male,42,9,222267.63,1,0,0,101108.85,1
3588,3589,15571958,McIntosh,489,Spain,Male,40,3,221532.80,1,1,0,171867.08,0
6717,6718,15586674,Shaw,663,Spain,Female,58,5,216109.88,1,0,1,74176.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0

In [19]:
# Accessing a Particualr Column:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [20]:
df.Balance # Won't Work if Column Name has Space in it

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [22]:
# Creating a Calculated Column based on Another Column:
df['New Balance'] = df['Balance'] + 1000
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82

In [23]:
df['Random Column'] = 'Random Value'
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00,Random Value
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86,Random Value
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80,Random Value
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00,Random Value
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82,Random Value

In [25]:
# Accessing Specific Rows:
df[10:15]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0,103016.72,Random Value
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,1000.00,Random Value
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0,1000.00,Random Value
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0,1000.00,Random Value
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0,1000.00,Random Value

In [28]:
# Filtering Records Based on Condition(s):
df[df['Age'] > 50]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88,Random Value
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32,Random Value
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35,Random Value
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11,Random Value
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00,Random Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0,1000.00,Random Value
9939,9940,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0,1000.00,Random Value
9948,9949,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0,140687.66,Random Value
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0,91022.85,Random Value
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1,89381.21,Random Value

In [31]:
# Filling Null Values in a Column:
df['Age'].fillna(0)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [32]:
# Creating New Dataframe Based on Condition:
new_df = df[df['Age'] > 50]
new_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance,Random Column
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88,Random Value
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32,Random Value
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35,Random Value
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11,Random Value
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00,Random Value

In [33]:
# Checking Shape of Dataframe:
print(new_df.shape)

(1261, 16)

In [34]:
# Removing a Column:
new_df.pop('Random Column')
new_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00

In [36]:
new_df.drop('New Balance', axis= 1, inplace= True)
new_df.head()

C:\Users\shail\AppData\Local\Temp\ipykernel_57380\2046262576.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop('New Balance', axis= 1, inplace= True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1

In [37]:
# Applying function on a Column:
new_df['Balance'].apply(np.sqrt)

16      364.146784
41      350.031884
42      342.665070
44      394.881134
58        0.000000
           ...
9936      0.000000
9939      0.000000
9948    373.748124
9979    300.038081
9991    297.289774
Name: Balance, Length: 1261, dtype: float64

In [38]:
# Drop Null Values from A Dataframe:
new_df.dropna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0
9939,9940,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0
9948,9949,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1

### Concat and Merge Dataframe:

In [39]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                   'B' : ['B0', 'B1', 'B2', 'B3'],
                   'C' : ['C0', 'C1', 'C2', 'C3'],
                   'D' : ['D0', 'D1', 'D2', 'D3']})

df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                   'B' : ['B4', 'B5', 'B6', 'B7'],
                   'C' : ['C4', 'C5', 'C6', 'C7'],
                   'D' : ['D4', 'D5', 'D6', 'D7']})

In [40]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [41]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [43]:
result = pd.concat([df1, df2])
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [44]:
df1 = pd.DataFrame({'Student_id': [1,2,3,4],
                   'Name': ['Bruce', 'Clark', 'Steve', 'Diana'],
                   'Age': [40, 33, 98, 356]})

df2 = pd.DataFrame({'Student_id': [2,3,4,5],
                   'Subject': ['Physics', 'Chemistry', 'Maths', 'Biology'],
                   'Marks': [56, 78, 99, 67]})

In [45]:
df1

   Student_id   Name  Age
0           1  Bruce   40
1           2  Clark   33
2           3  Steve   98
3           4  Diana  356

In [46]:
df2

   Student_id    Subject  Marks
0           2    Physics     56
1           3  Chemistry     78
2           4      Maths     99
3           5    Biology     67

In [47]:
# Inner Join:
merge_df = pd.merge(df1, df2, on= 'Student_id', how= 'inner')
merge_df

   Student_id   Name  Age    Subject  Marks
0           2  Clark   33    Physics     56
1           3  Steve   98  Chemistry     78
2           4  Diana  356      Maths     99

In [48]:
# Left Join:
merge_df = pd.merge(df1, df2, on = 'Student_id', how = 'left')
merge_df

   Student_id   Name  Age    Subject  Marks
0           1  Bruce   40        NaN    NaN
1           2  Clark   33    Physics   56.0
2           3  Steve   98  Chemistry   78.0
3           4  Diana  356      Maths   99.0

In [49]:
# Right Join:
merge_df = pd.merge(df1, df2, on = 'Student_id', how = 'right')
merge_df

   Student_id   Name    Age    Subject  Marks
0           2  Clark   33.0    Physics     56
1           3  Steve   98.0  Chemistry     78
2           4  Diana  356.0      Maths     99
3           5    NaN    NaN    Biology     67

In [50]:
# Full / Outer Join:
merge_df = pd.merge(df1, df2, on = 'Student_id', how = 'outer')
merge_df

   Student_id   Name    Age    Subject  Marks
0           1  Bruce   40.0        NaN    NaN
1           2  Clark   33.0    Physics   56.0
2           3  Steve   98.0  Chemistry   78.0
3           4  Diana  356.0      Maths   99.0
4           5    NaN    NaN    Biology   67.0

### loc vs iloc:

The main distinction between the two methods is:

- loc gets rows (and/or columns) with particular labels.

- iloc gets rows (and/or columns) at integer locations.

In [51]:
s = pd.Series(list('abcdef'), index= [49, 48, 47, 0, 1, 2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [52]:
# Value at Index Label 0:
s.loc[0]

'd'

In [53]:
# Value at Index Location 0:
s.iloc[0]

'a'

In [54]:
# Rows at Index Lables Between 0 and 1 (Inclusive):
s.loc[0:1]

0    d
1    e
dtype: object

In [55]:
# Rows at Index Location Between 0 and 1 (Exclusive):
s.iloc[0:1]

49    a
dtype: object

In [57]:
# Getting First two Elements of Series by lables:
s.loc[49:48]

49    a
48    b
dtype: object

In [59]:
# Getting First two Elements of Series by location:
s.iloc[0:2]

49    a
48    b
dtype: object