**Problem Statement:**
Google Play Store team is about to launch a new feature wherein, certain apps that are promising are boosted in visibility. The boost will
manifest in multiple ways including higher priority in recommendations sections (“Similar apps”, “You might also like”, “New and updated
games”). These will also get a boost in search results visibility. This feature will help bring more attention to newer apps that have the
potential.


**Analysis to be done:**
The problem is to identify the apps that are going to be good for Google to promote. App ratings, which are provided by the customers,
are always great indicators of the goodness of the app. The problem reduces to: predict which apps will have high ratings.

**Data Dictionary:**

Variables Description

- App: Application name

- Category: Category to which the app belongs

- Rating: Overall user rating of the app

- Reviews: Number of user reviews for the app

- Size: Size of the app

- Installs: Number of user downloads/installs for the app

- Type: Paid or Free

- Price: Price of the app

- Content: Rating Age group the app is targeted at - Children / Mature 21+ / Adult

- Genres: An app can belong to multiple genres (apart from its main category). For example, a musical family game will belong to Music, Game, Family genres

- Last: Updated Date when the app was last updated on Play Store

- Current Ver: Current version of the app available on Play Store

- Android Ver: Minimum required Android version

#### 1) Importing Necessary Libraries:

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, date

from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV,  ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.base import TransformerMixin, BaseEstimator

#### 2) Importing Data:

In [60]:
df = pd.read_csv('googleplaystore.csv')

In [61]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [62]:
df.shape

(10841, 13)

#### 3) Data Cleaning:

In [63]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [64]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content_Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

- Columns like Reviews, Size, Installs, Price should be numeric but are stored as Object type.

##### 1) Handling Wrong Data Types and Cleaning Data:

In [65]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

###### 1) Dropping Unnecesaary Columns:

- App: Name of the application is not a feature and is unique for all records, should be deleted.
- Current Ver: Current Version of the Application, not useful in analysis, should Be dropped.
- Android Ver: Required Android Version, not necessary for model building.

In [66]:
df.drop(['App','Current Ver', 'Android Ver'], axis= 1, inplace= True)

In [67]:
df.head()

         Category  Rating  ...                     Genres      Last Updated
0  ART_AND_DESIGN     4.1  ...               Art_&_Design   January 7, 2018
1  ART_AND_DESIGN     3.9  ...  Art_&_Design_Pretend_Play  January 15, 2018
2  ART_AND_DESIGN     4.7  ...               Art_&_Design    August 1, 2018
3  ART_AND_DESIGN     4.5  ...               Art_&_Design      June 8, 2018
4  ART_AND_DESIGN     4.3  ...    Art_&_Design_Creativity     June 20, 2018

[5 rows x 10 columns]

###### 2) Transforming Date and Android Version Columns:

In [68]:
df['Days Since Update'] = (pd.to_datetime(date.today()) - pd.to_datetime(df['Last Updated'], errors= 'coerce')).dt.days

In [70]:
df.drop('Last Updated', axis= 1, inplace= True)

In [71]:
df.head()

         Category  Rating  ...                     Genres Days Since Update
0  ART_AND_DESIGN     4.1  ...               Art_&_Design            2854.0
1  ART_AND_DESIGN     3.9  ...  Art_&_Design_Pretend_Play            2846.0
2  ART_AND_DESIGN     4.7  ...               Art_&_Design            2648.0
3  ART_AND_DESIGN     4.5  ...               Art_&_Design            2702.0
4  ART_AND_DESIGN     4.3  ...    Art_&_Design_Creativity            2690.0

[5 rows x 10 columns]